// build_sdk.mjs : generate the single-file, zero-dependency verifier nenrin_verify.mjs by concatenating the
// pinned nenrin modules in dependency order, stripping internal imports and deduping the shared node:crypto
// import and the repeated newAgentKey definition. Re-running is deterministic: same sources produce the same
// bundle byte for byte. This is a build tool, run on demand; the committed nenrin_verify.mjs is the artifact.
import { readFileSync, writeFileSync } from "node:fs";

const SOURCES = [
  "../task-delegation-bind-v0/bind.mjs",
  "../task-delegation-bind-v0/sign.mjs",
  "../task-execution-bind-v0/bind_exec.mjs",
  "../task-execution-bind-v0/sign_exec.mjs",
  "../task-execution-bind-v0/outcome_evidence.mjs",
  "../task-execution-bind-v0/preflight.mjs",
  "../provenance-v0/provenance_verify.mjs",
  "../provenance-v0/consume.mjs",
  "../provenance-v0/candidate_evidence.mjs",
];

const PRELUDE = `#!/usr/bin/env node
// nenrin_verify.mjs : single-file, zero-dependency verifier for a NENRIN provenance bundle.
//
// GENERATED by build_sdk.mjs from the pinned nenrin modules. Do not edit by hand; edit the sources and rebuild.
// Zero external dependencies: only Node built-ins. Copy this one file into your project and verify a NENRIN
// evidence bundle yourself, offline, with no trust in the operator:
//
//   node nenrin_verify.mjs bundle.json      # prints the provenance report, exit 0 if accepted, 1 if refused
//   import { verifyProvenance, consumeEvidence, publicKeyFromDidKey } from "./nenrin_verify.mjs"
//
// A bundle is { task_id, observations?, grant?, intent?, receipt|receipts?, require_signatures? } whose
// identifiers are did:key strings; the CLI resolves them to Ed25519 public keys with no network. Every hash and
// signature recomputes here; you do not take the operator's word for anything. Honest scope is carried in the
// report's does_not_establish: signatures prove who asserted and the linkage, not that any assertion is true,
// and there is no side-effect oracle.
import { createHash, sign as nodeSign, verify as nodeVerify, generateKeyPairSync, createPublicKey } from "node:crypto";
import { readFileSync, realpathSync } from "node:fs";
import { fileURLToPath } from "node:url";
`;

const EPILOGUE = `
// ---- did:key resolution (offline; Ed25519 public keys are self-encoded, no network, no key server) ----
const NENRIN_B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
function nenrinB58decode(str) {
  const bytes = [0];
  for (let i = 0; i < str.length; i++) {
    let carry = NENRIN_B58.indexOf(str[i]);
    if (carry < 0) throw new Error("bad base58 char");
    for (let j = 0; j < bytes.length; j++) { carry += bytes[j] * 58; bytes[j] = carry & 0xff; carry >>= 8; }
    while (carry > 0) { bytes.push(carry & 0xff); carry >>= 8; }
  }
  let zeros = 0; while (zeros < str.length && str[zeros] === "1") zeros++;
  const res = [];
  for (let z = 0; z < zeros; z++) res.push(0);
  for (let k = bytes.length - 1; k >= 0; k--) res.push(bytes[k]);
  return Uint8Array.from(res);
}
export function publicKeyFromDidKey(did) {
  if (typeof did !== "string" || !did.startsWith("did:key:z")) throw new Error("not a did:key");
  const payload = nenrinB58decode(did.slice("did:key:z".length));
  if (payload[0] !== 0xed || payload[1] !== 0x01) throw new Error("not an ed25519-pub did:key");
  const raw = Buffer.from(payload.slice(2));
  return createPublicKey({ key: { kty: "OKP", crv: "Ed25519", x: raw.toString("base64url") }, format: "jwk" });
}
export const didKeyResolver = (id) => { try { return publicKeyFromDidKey(id); } catch (e) { return null; } };

// ---- CLI: verify a bundle file offline and print the provenance report ----
function nenrinMain() {
  const path = process.argv[2];
  if (!path) { console.error("usage: node nenrin_verify.mjs <bundle.json>"); process.exit(2); }
  const bundle = JSON.parse(readFileSync(path, "utf8"));
  const input = Object.assign({}, bundle, { resolve: didKeyResolver });
  const report = verifyProvenance(input);
  console.log(JSON.stringify(report, null, 2));
  process.exit(report.verdict === "accepted" ? 0 : 1);
}
let nenrinIsMain = false;
try { nenrinIsMain = process.argv[1] && realpathSync(process.argv[1]) === fileURLToPath(import.meta.url); } catch (e) { nenrinIsMain = false; }
if (nenrinIsMain) nenrinMain();
`;

let out = PRELUDE;
let seenNewAgentKey = false;
const aliasLines = [];
for (const rel of SOURCES) {
  const src = readFileSync(new URL(rel, import.meta.url), "utf8");
  out += "\n// ============================== " + rel.replace(/^\.\.\//, "") + " ==============================\n";
  for (const line of src.split("\n")) {
    if (/^\s*import\s/.test(line)) {
      const m = line.match(/^\s*import\s*\{([^}]*)\}\s*from\s*["'](\.\.?\/[^"']+)["']/);
      if (m) for (const part of m[1].split(",")) { const am = part.trim().match(/^(\S+)\s+as\s+(\S+)$/); if (am) aliasLines.push("const " + am[2] + " = " + am[1] + ";"); }
      continue;
    }
    if (/^\s*export function newAgentKey\s*\(/.test(line)) {                // dedupe the shared helper
      if (seenNewAgentKey) continue;
      seenNewAgentKey = true;
    }
    out += line + "\n";
  }
}
if (aliasLines.length) out += "\n// ---- internal import aliases (restored from stripped aliased imports) ----\n" + [...new Set(aliasLines)].join("\n") + "\n";
out += EPILOGUE;
writeFileSync(new URL("./nenrin_verify.mjs", import.meta.url), out);
console.log("wrote nenrin_verify.mjs (" + out.split("\n").length + " lines) from " + SOURCES.length + " modules; newAgentKey deduped=" + seenNewAgentKey);
