#!/usr/bin/env node
// nenrin_verify.mjs : single-file, zero-dependency verifier for a NENRIN provenance bundle.
//
// GENERATED by build_sdk.mjs from the pinned nenrin modules. Do not edit by hand; edit the sources and rebuild.
// Zero external dependencies: only Node built-ins. Copy this one file into your project and verify a NENRIN
// evidence bundle yourself, offline, with no trust in the operator:
//
//   node nenrin_verify.mjs bundle.json      # prints the provenance report, exit 0 if accepted, 1 if refused
//   import { verifyProvenance, consumeEvidence, publicKeyFromDidKey } from "./nenrin_verify.mjs"
//
// A bundle is { task_id, observations?, grant?, intent?, receipt|receipts?, require_signatures? } whose
// identifiers are did:key strings; the CLI resolves them to Ed25519 public keys with no network. Every hash and
// signature recomputes here; you do not take the operator's word for anything. Honest scope is carried in the
// report's does_not_establish: signatures prove who asserted and the linkage, not that any assertion is true,
// and there is no side-effect oracle.
import { createHash, sign as nodeSign, verify as nodeVerify, generateKeyPairSync, createPublicKey } from "node:crypto";
import { readFileSync, realpathSync } from "node:fs";
import { fileURLToPath } from "node:url";

// ============================== task-delegation-bind-v0/bind.mjs ==============================
// task-delegation-bind-v0 : deterministic binding of an A2A Task id to NENRIN conduct evidence.
// 番人 reference impl (2026-09-16). Standard-track: anchors on the A2A Task `id` (v1.0 literal, tasks/get).
// Evidence rides ALONGSIDE the task (a sibling NENRIN record keyed by task_id), never inside a party-signed
// payload. That is the conferred-not-acquired line: the party under evaluation cannot mint its own verdict.
// Same primitive shape as the AP2 fair-price attestation (content hash + independent recompute + sibling carriage).

export const sha256hex = (s) => createHash("sha256").update(s, "utf8").digest("hex");

// simplified JCS: recursive key sort, no whitespace. Deterministic across implementations.
export function canonical(v) {
  if (v === null || typeof v !== "object") return JSON.stringify(v);
  if (Array.isArray(v)) return "[" + v.map(canonical).join(",") + "]";
  const keys = Object.keys(v).sort();
  return "{" + keys.map((k) => JSON.stringify(k) + ":" + canonical(v[k])).join(",") + "}";
}

// evidence_id = content hash over the preimage (the record minus derived/envelope fields).
// Signatures are excluded so adding them never changes evidence_id, and the witness signs the same bytes.
const DERIVED_FIELDS = ["evidence_id", "witness_sig", "edge_sig"];
export function preimage(obs) {
  const b = Object.assign({}, obs);
  for (const k of DERIVED_FIELDS) delete b[k];
  return b;
}
export function evidenceId(obs) {
  return sha256hex(canonical(preimage(obs)));
}

// R1 independence: the witness must not be either party of the hop it observes.
export function witnessIndependent(obs) {
  return obs.witness_id !== obs.hop.from && obs.witness_id !== obs.hop.to;
}

// R2 recompute: stored evidence_id must equal the recomputed content hash (detects tamper and bind-swap).
export function recomputeOk(obs) {
  return typeof obs.evidence_id === "string" && obs.evidence_id === evidenceId(obs);
}

// verify one observation on its own (R1 + R2).
export function verifyObservation(obs) {
  if (!witnessIndependent(obs)) return { ok: false, reason: "witness_not_independent" };
  if (!recomputeOk(obs)) return { ok: false, reason: "recompute_mismatch" };
  return { ok: true };
}

// R3 chain continuity: observations of one task, ordered by hop.seq, contiguous from 0, each linking the prior
// hop's evidence_id via prev_evidence_id. A hidden or forged hop breaks the link.
export function chainContinuous(observations) {
  const ord = observations.slice().sort((a, b) => a.hop.seq - b.hop.seq);
  for (let i = 0; i < ord.length; i++) {
    const o = ord[i];
    if (o.hop.seq !== i) return { ok: false, reason: "seq_gap", at: i };
    if (i === 0) {
      if (o.prev_evidence_id !== null) return { ok: false, reason: "root_prev_not_null", at: i };
    } else if (o.prev_evidence_id !== evidenceId(ord[i - 1])) {
      return { ok: false, reason: "broken_link", at: i };
    }
  }
  return { ok: true };
}

// R4 fail-closed aggregate: over the SET of witness observations for one {task_id, hop.seq}, differing verdicts
// aggregate to "disagreement", never collapse to the favorable one. A trust-signal read MUST return the full set,
// so a party cannot present a subset as consensus.
export function aggregateVerdict(observationsForHop) {
  const verdicts = [...new Set(observationsForHop.map((o) => o.conduct.verdict))];
  if (verdicts.length === 0) return "no_evidence";
  if (verdicts.length > 1) return "disagreement";
  return verdicts[0];
}


// ============================== task-delegation-bind-v0/sign.mjs ==============================
// Signature layer for task-delegation-bind-v0. Ed25519 detached signatures over the same canonical bytes
// as evidence_id. Wire form in production is a detached JWS (EdDSA); DIDs resolve to the public key
// (did:key is self-contained and needs no network). Here a resolver id -> publicKey stands in for DID resolution.
//
// Two signatures, two different jobs:
//  witness_sig : the witness signs its observation -> the verdict is ATTRIBUTABLE and non-repudiable (not spoofable).
//  edge_sig    : the delegating party (hop.from) signs {task_id, hop} -> the edge A->B is PARTY-ATTESTED,
//                not merely witness-claimed. This closes the self-asserted-chain hole at the party level.
// Honest line: signatures prove WHO asserted, not that the assertion is TRUE. Combined with R1 (independent
// witness) and R4 (disagreement surfaced) you get attributable + independent + non-suppressible observations.

export function newAgentKey() { return generateKeyPairSync("ed25519"); } // { publicKey, privateKey } KeyObjects

const edgeOf = (obs) => ({ task_id: obs.task_id, hop: obs.hop });

export function signObservation(obs, witnessPriv) {
  const sig = nodeSign(null, Buffer.from(canonical(preimage(obs)), "utf8"), witnessPriv);
  return Object.assign({}, obs, { witness_sig: sig.toString("base64") });
}
export function signEdge(obs, fromPriv) {
  const sig = nodeSign(null, Buffer.from(canonical(edgeOf(obs)), "utf8"), fromPriv);
  return Object.assign({}, obs, { edge_sig: sig.toString("base64") });
}
export function verifyWitnessSig(obs, witnessPub) {
  if (typeof obs.witness_sig !== "string" || !witnessPub) return false;
  try { return nodeVerify(null, Buffer.from(canonical(preimage(obs)), "utf8"), witnessPub, Buffer.from(obs.witness_sig, "base64")); }
  catch (e) { return false; }
}
export function verifyEdgeSig(obs, fromPub) {
  if (typeof obs.edge_sig !== "string" || !fromPub) return false;
  try { return nodeVerify(null, Buffer.from(canonical(edgeOf(obs)), "utf8"), fromPub, Buffer.from(obs.edge_sig, "base64")); }
  catch (e) { return false; }
}
// signed verify: witness signature (attribution) + edge signature (party-attested edge). resolve: id -> publicKey.
export function verifySigned(obs, resolve) {
  if (!verifyWitnessSig(obs, resolve(obs.witness_id))) return { ok: false, reason: "witness_sig_invalid" };
  if (!verifyEdgeSig(obs, resolve(obs.hop.from))) return { ok: false, reason: "edge_sig_invalid" };
  return { ok: true };
}


// ============================== task-execution-bind-v0/bind_exec.mjs ==============================
// task-execution-bind-v0 : deterministic binding of an AUTHORIZED action to its EXECUTION receipt,
// at the caller/gateway execution boundary. Composable counterpart to task-delegation-bind-v0
// (third-party observation) and to Poke-nushi's VATE (a2aproject/A2A#1769). VATE is the artifact of
// record for this boundary; this is a minimal, swappable reference implementation whose only job is to
// make the composition seam testable end to end. It claims no ownership of the boundary.
//
// It supplies exactly the two properties boundary_case.test.mjs proved the observation layer is silent on:
//   E1 authorized-action match : did the executed action equal the authorized one?
//   E2 outcome reconciliation  : after a lost response, is the outcome recoverable, and is provider
//                                equivocation DETECTABLE rather than launderable into the favorable one?
//   E3 grant binding           : the receipt commits to the grant by hash INSIDE the provider's signed bytes.
//
// A grant names the authorized executor (provider_id). Scoping reconciliation to that executor is what makes
// equivocation attributable and closes the forge-a-second-receipt griefing path (see sign_exec.reconcileSigned).
//
// Honest line (the same wall as the observation layer): a signature proves WHO asserted, not that the
// assertion is TRUE. E1 compares two SIGNED statements (a caller's authorization and a provider's receipt);
// it establishes that the provider's CLAIMED action matches the authorization, not that the provider
// performed it in the world. E2 makes a lost outcome recoverable and equivocation detectable; it does NOT
// prevent equivocation and does NOT prove the reconciled outcome is the real-world outcome.

// Derived/envelope fields, excluded from the content hash so signing never changes the hash and the
// signer signs the same bytes the verifier recomputes. Same discipline as evidence_id in bind.mjs.
const GRANT_DERIVED = ["grant_ref", "caller_sig"];
const RECEIPT_DERIVED = ["receipt_id", "provider_sig"];

function stripped(rec, derived) {
  const b = Object.assign({}, rec);
  for (const k of derived) delete b[k];
  return b;
}
export const grantPreimage = (g) => stripped(g, GRANT_DERIVED);
export const receiptPreimage = (r) => stripped(r, RECEIPT_DERIVED);
export const grantRef = (g) => sha256hex(canonical(grantPreimage(g)));
export const receiptId = (r) => sha256hex(canonical(receiptPreimage(r)));

// action equality by canonical bytes (tool, target, args_sha256), order-independent, extra fields diverge.
export function actionsEqual(a, b) {
  return !!a && !!b && canonical(a) === canonical(b);
}

// self-authorization (declared, not refused): the grant's caller authorized its own executor.
// Evaluated on the GRANT (who authorized whom), not on who happened to sign a receipt.
export function grantIsSelfAuthorized(g) {
  return g.provider_id != null && g.caller_id === g.provider_id;
}

// the receipt must come from the executor the grant authorized. A grant with provider_id null is an open
// grant (any executor); v0 records that as a finding rather than silently accepting it.
export function providerAuthorized(g, r) {
  return g.provider_id == null || r.provider_id === g.provider_id;
}

// E3: recompute grant_ref and require the receipt to reference THIS grant by that hash.
export function receiptBindsGrant(g, r) {
  return typeof r.grant_ref === "string" && r.grant_ref === grantRef(g);
}

// strict RFC3339 UTC ("...Z") timestamp. v0 requires UTC Z form so a non-UTC offset or a date-only
// string cannot slip an execution past the window via Date.parse laxity.
const RFC3339_UTC = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/;
export function isRfc3339Utc(s) { return typeof s === "string" && RFC3339_UTC.test(s) && !Number.isNaN(Date.parse(s)); }

// validity window: executed_at within [not_before, not_after]; both bounds live in the signed grant.
export function withinWindow(g, r) {
  const t = Date.parse(r.executed_at);
  if (Number.isNaN(t)) return false;
  if (g.not_before != null) { const nb = Date.parse(g.not_before); if (Number.isNaN(nb) || t < nb) return false; }
  if (g.not_after != null) { const na = Date.parse(g.not_after); if (Number.isNaN(na) || t > na) return false; }
  return true;
}

// E1: does the provider's executed_action match the caller's authorized action?
export function actionMatch(g, r) {
  if (!actionsEqual(g.action, r.executed_action)) return { ok: false, reason: "action_diverged" };
  return { ok: true };
}

// R2-style recompute for each record on its own (detects tamper and bind-swap).
export function grantRecomputeOk(g) { return typeof g.grant_ref === "string" && g.grant_ref === grantRef(g); }
export function receiptRecomputeOk(r) { return typeof r.receipt_id === "string" && r.receipt_id === receiptId(r); }

// verify a grant+receipt pair (content-addressed core; signatures handled in sign_exec.mjs).
// findings carries DECLARED, non-fatal disclosures (mirrors the conduct_self_measured finding in agreement-v0).
export function verifyExecution(g, r) {
  const findings = [];
  if (!grantRecomputeOk(g)) return { ok: false, reason: "grant_recompute_mismatch", findings };
  if (!receiptRecomputeOk(r)) return { ok: false, reason: "receipt_recompute_mismatch", findings };
  if (!receiptBindsGrant(g, r)) return { ok: false, reason: "receipt_unbound", findings };
  if (!isRfc3339Utc(r.executed_at) || (g.not_before != null && !isRfc3339Utc(g.not_before)) || (g.not_after != null && !isRfc3339Utc(g.not_after)))
    return { ok: false, reason: "invalid_timestamp", findings };
  if (!providerAuthorized(g, r)) return { ok: false, reason: "provider_not_authorized", findings };
  if (!withinWindow(g, r)) return { ok: false, reason: "outside_authorization_window", findings };
  if (g.provider_id == null) findings.push({ code: "open_grant", why: "the grant names no provider_id, so any executor's receipt is accepted; this pair does not establish that the executor was the one the caller intended." });
  if (grantIsSelfAuthorized(g)) findings.push({ code: "self_authorized", why: "caller_id equals the grant's provider_id; the caller authorized its own executor. Declared, so recorded not refused; this pair does not establish that the authorization came from anyone other than the executor." });
  const e1 = actionMatch(g, r);
  return { ok: e1.ok, reason: e1.ok ? "action_bound" : e1.reason, findings };
}

// E2 (sig-free) reconciliation over a SET of receipts for one grant_ref. Fail-closed like R4: conflicting
// committed outcomes yield "equivocation", never the favorable one. A lost response is recovered by
// re-querying this set and finding the byte-identical receipt. NOTE: without signatures this reports only
// STRUCTURAL conflict; a third party could forge a second receipt. Attributable equivocation is in sign_exec.
export function reconcileOutcome(receipts, grant_ref) {
  const forGrant = receipts.filter((r) => r.grant_ref === grant_ref && receiptRecomputeOk(r));
  const ids = [...new Set(forGrant.map((r) => r.receipt_id))];
  if (ids.length === 0) return { status: "no_receipt" };
  if (ids.length > 1) return { status: "equivocation", receipt_ids: ids };
  return { status: "reconciled", receipt_id: ids[0], outcome: forGrant[0].outcome };
}


// ============================== task-execution-bind-v0/sign_exec.mjs ==============================
// Signature layer for task-execution-bind-v0. Two Ed25519 detached signatures, two jobs:
//   caller_sig   : the caller signs canonical(grantPreimage). The authorization is ATTRIBUTABLE to the caller.
//   provider_sig : the provider signs canonical(receiptPreimage), which INCLUDES grant_ref, so the receipt is
//                  bound to that specific grant and attributable to the provider (non-repudiable).
// Wire form in production is a detached JWS (EdDSA); DIDs resolve to the public key (did:key is self-contained,
// no network). Here a resolver id -> publicKey stands in for DID resolution, exactly as in sign.mjs.
// Honest line: signatures prove WHO asserted, not that the assertion is TRUE.


export function signGrant(g, callerPriv) {
  const sig = nodeSign(null, Buffer.from(canonical(grantPreimage(g)), "utf8"), callerPriv);
  return Object.assign({}, g, { caller_sig: sig.toString("base64") });
}
export function signReceipt(r, providerPriv) {
  const sig = nodeSign(null, Buffer.from(canonical(receiptPreimage(r)), "utf8"), providerPriv);
  return Object.assign({}, r, { provider_sig: sig.toString("base64") });
}
export function verifyGrantSig(g, callerPub) {
  if (typeof g.caller_sig !== "string" || !callerPub) return false;
  try { return nodeVerify(null, Buffer.from(canonical(grantPreimage(g)), "utf8"), callerPub, Buffer.from(g.caller_sig, "base64")); }
  catch (e) { return false; }
}
export function verifyReceiptSig(r, providerPub) {
  if (typeof r.provider_sig !== "string" || !providerPub) return false;
  try { return nodeVerify(null, Buffer.from(canonical(receiptPreimage(r)), "utf8"), providerPub, Buffer.from(r.provider_sig, "base64")); }
  catch (e) { return false; }
}
// signed pair verify: caller authorized (caller_sig) + provider receipted (provider_sig). resolve: id -> publicKey.
export function verifySignedExecution(g, r, resolve) {
  if (!verifyGrantSig(g, resolve(g.caller_id))) return { ok: false, reason: "caller_sig_invalid" };
  if (!verifyReceiptSig(r, resolve(r.provider_id))) return { ok: false, reason: "provider_sig_invalid" };
  return { ok: true };
}
// Attributable reconciliation, scoped to the executor the grant AUTHORIZED. A receipt counts only if it
// references this grant_ref, recomputes, declares provider_id === authorizedProvider, AND carries a valid
// provider_sig from that provider's key. This closes both forge-a-second-receipt griefing paths: a stranger
// signing under its own id is not the authorized executor (provider_id mismatch), and a stranger impersonating
// the executor's id fails the signature check against the real key. Genuine equivocation (the authorized
// executor itself signing two conflicting outcomes for one grant_ref) is surfaced fail-closed, never laundered.
export function reconcileSigned(receipts, grant_ref, authorizedProvider, resolve) {
  if (authorizedProvider == null) return { status: "no_authorized_provider" }; // open grants are not reconcilable; name the executor
  const authentic = receipts.filter((r) =>
    r.grant_ref === grant_ref &&
    r.provider_id === authorizedProvider &&
    r.receipt_id === receiptId(r) &&
    verifyReceiptSig(r, resolve(authorizedProvider)));
  const ids = [...new Set(authentic.map((r) => r.receipt_id))];
  if (ids.length === 0) return { status: "no_authentic_receipt" };
  if (ids.length > 1) return { status: "equivocation", receipt_ids: ids, provider_id: authorizedProvider };
  return { status: "reconciled", receipt_id: ids[0], outcome: authentic[0].outcome };
}


// ============================== task-execution-bind-v0/outcome_evidence.mjs ==============================
// outcome_evidence.mjs : outcome-evidence binding for task-execution-bind-v0.
//
// Moves an execution outcome from "the provider claims X" to "the provider commits, under its signature, to a
// pointer E in an independently verifiable system S, which anyone can check without the provider's help".
// The binding is cryptographic: evidence sits inside receipt.outcome, so receipt_id and provider_sig cover it
// (a mutated pointer breaks both). The ground-truth check of E in S is delegated to S itself. This module opens
// no socket and has no clock. An operator MAY inject lookup(evidence) -> { found, matches } to confirm E in S;
// the result says whether such a lookup ran, so a reader never mistakes "bound" for "confirmed".
//
// Honest line: binding proves WHAT the provider pointed at, not that the pointer resolves or that it says what
// the provider claims. Only the reader, or an injected lookup, can establish that, and the report states which.
const HEX64 = /^[0-9a-f]{64}$/;

// kinds v0 understands. ref format is checked; the system string names where a reader goes to check.
export const EVIDENCE_KINDS = {
  bitcoin_tx: { ref: HEX64, means: "a Bitcoin transaction id; a reader checks it on any node or explorer" },
  ledger_record: { ref: HEX64, means: "a content-addressed ledger record sha256; a reader fetches the bytes and recomputes" },
  document_sha256: { ref: HEX64, means: "sha256 of a document the reader can obtain and hash" },
  url_sha256: { ref: HEX64, means: "sha256 of the bytes served at a url the reader can fetch and hash" },
};

export function evidenceOf(receipt) {
  return receipt && receipt.outcome && receipt.outcome.evidence ? receipt.outcome.evidence : null;
}

// shape check only: known kind, ref matches the kind's format, non-empty system.
export function evidenceWellFormed(ev) {
  if (!ev || typeof ev !== "object") return { ok: false, reason: "evidence_not_object" };
  const k = EVIDENCE_KINDS[ev.kind];
  if (!k) return { ok: false, reason: "evidence_kind_unknown" };
  if (typeof ev.ref !== "string" || !k.ref.test(ev.ref)) return { ok: false, reason: "evidence_ref_malformed" };
  if (typeof ev.system !== "string" || ev.system.length === 0) return { ok: false, reason: "evidence_system_missing" };
  return { ok: true };
}

// verify the evidence bound to a receipt. lookup is optional and injected; when present it is called ONCE with
// the evidence object and must return { found: boolean, matches: boolean }. Any throw is treated as not confirmed.
// Returns { ok, reason, bound, checked_externally, external? }.
export function verifyEvidence(receipt, lookup) {
  const ev = evidenceOf(receipt);
  if (!ev) return { ok: true, reason: "no_evidence_bound", bound: false, checked_externally: false };
  const w = evidenceWellFormed(ev);
  if (!w.ok) return { ok: false, reason: w.reason, bound: true, checked_externally: false };
  if (typeof lookup !== "function") return { ok: true, reason: "evidence_bound_unchecked", bound: true, checked_externally: false };
  let ext;
  try { ext = lookup(ev); } catch (e) { ext = { found: false, matches: false, error: String(e && e.message || e) }; }
  const found = !!(ext && ext.found), matches = !!(ext && ext.matches);
  if (!found) return { ok: false, reason: "evidence_not_found", bound: true, checked_externally: true, external: { found, matches } };
  if (!matches) return { ok: false, reason: "evidence_does_not_match", bound: true, checked_externally: true, external: { found, matches } };
  return { ok: true, reason: "evidence_confirmed", bound: true, checked_externally: true, external: { found, matches } };
}


// ============================== task-execution-bind-v0/preflight.mjs ==============================
// preflight.mjs : pre-execution authorization evidence for task-execution-bind-v0.
//
// The execution layer binds an action AFTER it ran (grant + receipt). This binds it BEFORE, at the moment a
// provider declares what it is about to do (grant + intent). Same primitive, the other side of the action:
//   grant   : the caller signs WHAT it authorizes (action, provider, window).
//   intent  : the provider signs WHAT it is about to do, referencing the grant by hash, before executing.
//   receipt : the provider signs WHAT it did, after executing (../bind_exec.mjs).
// All three carry the same grant_ref, so a verifier can later check declared == authorized == executed.
//
// WHAT THIS IS NOT. This does not decide whether to transact. It returns no allow/deny and no trust score.
// HORIZON SHIELD stays on the evidence side of the line: it establishes, before execution, whether a declared
// action is inside a grant the caller signed, and it surfaces the counterparty's evidence posture as MATERIAL.
// The decision belongs to the caller's own gateway (or a policy engine such as SINT or PHION), which may
// consume this evidence. Turning this into an allow/deny engine would abandon the one property that makes the
// evidence worth anything: that HORIZON SHIELD is not the party deciding.
//
// Honest line (same wall as every layer): a signature proves WHO asserted, not that the assertion is TRUE.
// "preauthorized" means the provider's DECLARED action matches the caller's signed grant. It does not promise
// the provider will execute that action; the receipt, checked afterward, is what catches a provider that
// declared one thing and did another.

const INTENT_DERIVED = ["intent_id", "intent_sig"];
export const intentPreimage = (i) => { const b = Object.assign({}, i); for (const k of INTENT_DERIVED) delete b[k]; return b; };
export const intentId = (i) => sha256hex(canonical(intentPreimage(i)));
export function intentRecomputeOk(i) { return typeof i.intent_id === "string" && i.intent_id === intentId(i); }
export function intentBindsGrant(g, i) { return typeof i.grant_ref === "string" && i.grant_ref === grantRef(g); }

function declaredInWindow(g, i) {
  const t = Date.parse(i.declared_at);
  if (Number.isNaN(t)) return false;
  if (g.not_before != null) { const nb = Date.parse(g.not_before); if (Number.isNaN(nb) || t < nb) return false; }
  if (g.not_after != null) { const na = Date.parse(g.not_after); if (Number.isNaN(na) || t > na) return false; }
  return true;
}

// verify a grant + intent pair BEFORE execution. Returns { ok, reason, findings }.
// ok true with reason "preauthorized" means: the declared action is inside a grant the caller signed, the
// declaring provider is the authorized executor, and the declaration falls in the grant window. It is a FACT
// about the intent, not a recommendation to proceed.
export function verifyPreflight(g, i) {
  const findings = [];
  if (!grantRecomputeOk(g)) return { ok: false, reason: "grant_recompute_mismatch", findings };
  if (!intentRecomputeOk(i)) return { ok: false, reason: "intent_recompute_mismatch", findings };
  if (!intentBindsGrant(g, i)) return { ok: false, reason: "intent_unbound", findings };
  if (!isRfc3339Utc(i.declared_at) || (g.not_before != null && !isRfc3339Utc(g.not_before)) || (g.not_after != null && !isRfc3339Utc(g.not_after)))
    return { ok: false, reason: "invalid_timestamp", findings };
  if (!providerAuthorized(g, i)) return { ok: false, reason: "provider_not_authorized", findings };
  if (!declaredInWindow(g, i)) return { ok: false, reason: "outside_authorization_window", findings };
  if (g.provider_id == null) findings.push({ code: "open_grant", why: "the grant names no provider_id, so any declaring executor is accepted; this pair does not establish the caller intended this executor." });
  if (grantIsSelfAuthorized(g)) findings.push({ code: "self_authorized", why: "caller_id equals the grant's provider_id; the caller authorized its own executor." });
  if (!actionsEqual(g.action, i.proposed_action)) return { ok: false, reason: "action_diverged", findings };
  return { ok: true, reason: "preauthorized", findings };
}

// declared == executed. The three-way match (authorized == declared == executed) is verifyPreflight ok on the
// grant+intent AND verifyExecution ok on the grant+receipt AND this, which catches a provider that declared one
// action and executed another even when both individually reference the grant.
export function intentMatchesReceipt(i, r) { return actionsEqual(i.proposed_action, r.executed_action); }

// Counterparty posture: MATERIAL for the caller's decision, never a score or a verdict. Surfaces where the
// counterparty's presented prior evidence carries unresolved disagreement (observations) or equivocation
// (receipts). Absence of conflict is NOT evidence of good conduct; it may only mean no evidence was presented.
export function counterpartyPosture(priorObservations, priorReceipts) {
  const obs = Array.isArray(priorObservations) ? priorObservations : [];
  const rcpts = Array.isArray(priorReceipts) ? priorReceipts : [];
  const byHop = new Map();
  for (const o of obs) { const k = JSON.stringify([o && o.task_id, o && o.hop ? o.hop.seq : null]); if (!byHop.has(k)) byHop.set(k, []); byHop.get(k).push(o); }
  const unresolved_disagreements = [];
  for (const [k, set] of byHop) if (aggregateVerdict(set) === "disagreement") unresolved_disagreements.push({ at: k, witnesses: set.map((o) => o.witness_id) });
  const byGrant = new Map();
  for (const r of rcpts) { const k = r && r.grant_ref; if (!byGrant.has(k)) byGrant.set(k, []); byGrant.get(k).push(r); }
  const equivocations = [];
  for (const [k, set] of byGrant) { const rec = reconcileOutcome(set, k); if (rec.status === "equivocation") equivocations.push({ grant_ref: k, receipt_ids: rec.receipt_ids }); }
  return {
    prior_observation_hops: byHop.size,
    prior_receipt_grants: byGrant.size,
    unresolved_disagreements,
    equivocations,
    note: "material for the caller's own decision, not a score and not a recommendation; absence of conflict here is not evidence of good conduct, only that none was presented",
  };
}

// signature layer for the intent: the provider signs canonical(intentPreimage), which includes grant_ref, so
// the declaration is bound to the grant and attributable to the provider.
export function signIntent(i, providerPriv) {
  const sig = nodeSign(null, Buffer.from(canonical(intentPreimage(i)), "utf8"), providerPriv);
  return Object.assign({}, i, { intent_sig: sig.toString("base64") });
}
export function verifyIntentSig(i, providerPub) {
  if (typeof i.intent_sig !== "string" || !providerPub) return false;
  try { return nodeVerify(null, Buffer.from(canonical(intentPreimage(i)), "utf8"), providerPub, Buffer.from(i.intent_sig, "base64")); }
  catch (e) { return false; }
}

// the whole pre-execution evidence bundle, in the a2a-agreement-verify-v0 report idiom.
// input: { grant, intent, priorObservations?, priorReceipts?, resolve?, require_signature? (default true) }
export function preflightReport(input) {
  const g = input.grant, i = input.intent;
  const resolve = typeof input.resolve === "function" ? input.resolve : () => null;
  const requireSig = input.require_signature !== false;
  const findings = [];
  const pf = verifyPreflight(g, i);
  pf.findings.forEach((f) => findings.push(f));
  let sig_ok = true, sig_reason = "signature_not_required";
  if (requireSig) { sig_ok = verifyIntentSig(i, resolve(i.provider_id)); sig_reason = sig_ok ? "intent_sig_valid" : "intent_sig_invalid"; }
  const authorized = pf.ok && sig_ok;
  const posture = counterpartyPosture(input.priorObservations, input.priorReceipts);
  const establishes = [];
  if (authorized) {
    establishes.push("the declared action equals, byte for byte, the action the caller signed in the grant (grant_ref " + g.grant_ref + ")");
    establishes.push("the declaring provider is the executor the grant authorized, and the declaration falls in the grant window");
    if (requireSig) establishes.push("the intent carries a valid provider signature over its own bytes, attributable to " + i.provider_id);
  } else {
    establishes.push("nothing about authorization: " + (pf.ok ? sig_reason : pf.reason));
  }
  const does_not_establish = [
    "this is NOT a decision to proceed: HORIZON SHIELD returns evidence, not allow or deny, and no trust score; the caller's own gateway decides",
    "that the provider will execute the action it declared: the receipt, checked after execution, is what catches a declared-then-diverged action",
    "that the counterparty is trustworthy: the posture surfaces presented conflicts as material, and absence of conflict is not evidence of good conduct",
    "that any action occurred in the world: this is a pre-execution declaration, and no signature has a side-effect oracle",
  ];
  return { schema: "task-preflight-v0", task_id: g && g.task_id, authorized, status: pf.reason, signature: sig_reason, findings, counterparty_posture: posture, establishes, does_not_establish };
}


// ============================== provenance-v0/provenance_verify.mjs ==============================
// nenrin-provenance-verify-v0 : one verifier over the whole provenance graph of one A2A task.
//
// It composes three layers that each stand on their own and imports their pinned primitives unchanged:
//   task-delegation-bind-v0 : third-party OBSERVATION of the delegation chain (R1..R4, witness_sig, edge_sig)
//   task-execution-bind-v0  : caller/gateway ACTION + OUTCOME binding (E1..E3, caller_sig, provider_sig)
//   outcome_evidence        : the outcome's commitment to an independently checkable pointer
// and adds the cross-layer checks no single layer can make: task identity across every record, and the
// digest-bound linkage from an observation to the reconciled receipt. It opens no socket and has no clock.
// Key resolution (resolve) and evidence confirmation (lookup) are injected, exactly like the layers below.
//
// Report shape mirrors a2a-agreement-verify-v0: verdict, refusals, findings, establishes, does_not_establish.
// Fail-closed for readers: a refused report establishes nothing; disagreement and equivocation are surfaced,
// never collapsed into the favorable outcome. The wall that no signature can cross (no side-effect oracle) is
// written into does_not_establish on every report, accepted or refused.

export const VERIFIER_VERSION = "0.1.0";
export const LINK_PREFIX = "nenrin-exec://";

// R3 generalized to a SET with possibly several witnesses per hop: seqs contiguous from 0, every root has a
// null prev, and every non-root prev_evidence_id resolves to SOME presented observation of the prior hop.
// With exactly one witness per hop this is the pinned chainContinuous, and provenance_adversarial asserts that.
export function chainContinuousSet(observations) {
  const bySeq = new Map();
  for (const o of observations) {
    const s = o && o.hop ? o.hop.seq : undefined;
    if (!bySeq.has(s)) bySeq.set(s, []);
    bySeq.get(s).push(o);
  }
  const seqs = [...bySeq.keys()].sort((a, b) => a - b);
  for (let i = 0; i < seqs.length; i++) if (seqs[i] !== i) return { ok: false, reason: "seq_gap", at: i };
  for (const s of seqs) {
    for (const o of bySeq.get(s)) {
      if (s === 0) { if (o.prev_evidence_id !== null) return { ok: false, reason: "root_prev_not_null", at: 0 }; }
      else {
        const prior = new Set(bySeq.get(s - 1).map(evidenceId));
        if (!prior.has(o.prev_evidence_id)) return { ok: false, reason: "broken_link", at: s };
      }
    }
  }
  return { ok: true };
}

export function verifyProvenance(input) {
  const task_id = input && input.task_id;
  const observations = Array.isArray(input.observations) ? input.observations : [];
  const grant = input.grant || null;
  const primaryReceipt = input.receipt || null;
  const receipts = Array.isArray(input.receipts) && input.receipts.length ? input.receipts : (primaryReceipt ? [primaryReceipt] : []);
  const resolve = typeof input.resolve === "function" ? input.resolve : () => null;
  const lookup = typeof input.lookup === "function" ? input.lookup : null;
  const requireSigs = input.require_signatures !== false;
  const intent = input.intent || null;

  const refusals = [], findings = [];
  const refuse = (code, why, extra) => refusals.push(Object.assign({ code, why }, extra || {}));
  const note = (code, why, extra) => findings.push(Object.assign({ code, why }, extra || {}));
  const layers = { identity: null, delegation: null, execution: null, preflight: null, evidence: null, linkage: null };

  // ---- 0. task identity across every presented record ----
  if (typeof task_id !== "string" || task_id.length === 0) refuse("task_id_missing", "input.task_id must be a non-empty string");
  const idChecks = [];
  observations.forEach((o, i) => idChecks.push({ record: "observation[" + i + "]", id: o && o.task_id }));
  if (grant) idChecks.push({ record: "grant", id: grant.task_id });
  if (intent) idChecks.push({ record: "intent", id: intent.task_id });
  receipts.forEach((r, i) => idChecks.push({ record: "receipt[" + i + "]", id: r && r.task_id }));
  const mismatched = idChecks.filter((c) => c.id !== task_id).map((c) => c.record);
  layers.identity = { records: idChecks.length, mismatched };
  if (mismatched.length) refuse("task_id_mismatch", "every record must carry the task_id under verification", { records: mismatched });

  // ---- 1. delegation layer (observation) ----
  if (observations.length === 0) {
    layers.delegation = { present: false };
    note("no_delegation_observations", "no third-party observation of the delegation chain was presented; the execution layer is verified on its own");
  } else {
    const per = observations.map((o, i) => {
      const v = verifyObservation(o);
      const s = requireSigs ? verifyObservationSigned(o, resolve) : { ok: true, reason: "signatures_not_required" };
      return { index: i, seq: o.hop && o.hop.seq, witness_id: o.witness_id, ok: v.ok && s.ok, reason: v.ok ? (s.ok ? "ok" : s.reason) : v.reason };
    });
    per.filter((p) => !p.ok).forEach((p) => refuse("delegation_observation_invalid", "an observation failed R1/R2 or its signatures", { index: p.index, seq: p.seq, reason: p.reason }));
    const chain = chainContinuousSet(observations);
    if (!chain.ok) refuse("delegation_chain_broken", "hop continuity (R3) does not hold over the presented set", { reason: chain.reason, at: chain.at });
    const bySeq = new Map();
    for (const o of observations) { const s = o.hop && o.hop.seq; if (!bySeq.has(s)) bySeq.set(s, []); bySeq.get(s).push(o); }
    const hop_verdicts = [...bySeq.keys()].sort((a, b) => a - b).map((s) => ({ seq: s, verdict: aggregateVerdict(bySeq.get(s)), witnesses: bySeq.get(s).map((o) => o.witness_id) }));
    hop_verdicts.filter((h) => h.verdict === "disagreement").forEach((h) => note("witness_disagreement", "witnesses of one hop disagree; the aggregate is disagreement, not the favorable verdict (R4)", { seq: h.seq, witnesses: h.witnesses }));
    layers.delegation = { present: true, observations: per, chain, hop_verdicts };
  }

  // ---- 2. execution layer (grant + receipt) ----
  let reconciledReceipt = null;
  if (!grant && receipts.length === 0) {
    layers.execution = { present: false };
    note("no_execution_records", "no grant/receipt pair was presented; the delegation layer is verified on its own");
  } else if (!grant || receipts.length === 0) {
    layers.execution = { present: true, complete: false };
    refuse("execution_incomplete_pair", "a grant and at least one receipt are both required to verify execution");
  } else {
    const primary = primaryReceipt || receipts[0];
    const ve = verifyExecution(grant, primary);
    ve.findings.forEach((f) => note(f.code, f.why));
    if (!ve.ok) refuse("execution_invalid", "the grant/receipt pair failed recompute, binding, window or E1", { reason: ve.reason });
    let sigs = { ok: true, reason: "signatures_not_required" };
    if (requireSigs) { sigs = verifySignedExecution(grant, primary, resolve); if (!sigs.ok) refuse("execution_signature_invalid", "caller_sig or provider_sig does not verify", { reason: sigs.reason }); }
    const rec = requireSigs ? reconcileSigned(receipts, grant.grant_ref, grant.provider_id, resolve) : reconcileOutcome(receipts, grant.grant_ref);
    if (rec.status === "equivocation") refuse("execution_equivocation", "the authorized provider signed conflicting outcomes for one grant; no single outcome can be established (E2, fail-closed)", { receipt_ids: rec.receipt_ids });
    else if (rec.status !== "reconciled") refuse("execution_unreconciled", "no authentic receipt reconciles this grant", { status: rec.status });
    else reconciledReceipt = receipts.find((r) => r.receipt_id === rec.receipt_id) || primary;
    layers.execution = { present: true, complete: true, pair: ve.reason, signatures: sigs.reason, reconciliation: rec.status, receipt_id: rec.receipt_id || null, outcome: rec.outcome || null };
  }

  // ---- 2b. preflight layer (pre-execution intent), when an intent is presented ----
  if (!intent) {
    layers.preflight = { present: false };
  } else if (!grant) {
    layers.preflight = { present: true, complete: false };
    refuse("preflight_without_grant", "an intent was presented without a grant; a pre-execution declaration can only be checked against the grant it references");
  } else {
    const pf = verifyPreflight(grant, intent);
    pf.findings.forEach((f) => note(f.code, f.why));
    if (!pf.ok) refuse("preflight_invalid", "the pre-execution intent is not authorized by the grant", { reason: pf.reason });
    let isig = { ok: true, reason: "signatures_not_required" };
    if (requireSigs) { const ok = verifyIntentSig(intent, resolve(intent.provider_id)); isig = { ok, reason: ok ? "intent_sig_valid" : "intent_sig_invalid" }; if (!ok) refuse("preflight_signature_invalid", "the intent signature does not verify", { reason: isig.reason }); }
    let declared_matches_executed = null;
    // Under a fixed-action grant, declared == executed is IMPLIED once preflight (declared == grant action) and
    // execution E1 (executed == grant action) both pass, so a divergence here always coincides with a
    // preflight_invalid or execution_invalid refusal already raised. We therefore record it as a framing note,
    // not an independent refusal, so the report never double-counts nor overclaims a distinct catch. The real,
    // non-redundant value of the intent is temporal: a signed pre-execution PROMISE, checkable before the receipt exists.
    if (reconciledReceipt) { declared_matches_executed = intentMatchesReceipt(intent, reconciledReceipt); if (!declared_matches_executed) note("declared_executed_divergence", "the pre-execution declaration and the executed action differ; the individual preflight or execution refusal above is the operative one"); }
    layers.preflight = { present: true, complete: true, status: pf.reason, signature: isig.reason, declared_matches_executed };
  }

  // ---- 3. evidence layer (on the reconciled receipt) ----
  const evReceipt = reconciledReceipt || primaryReceipt || receipts[0] || null;
  if (evReceipt) {
    const vev = verifyEvidence(evReceipt, lookup);
    layers.evidence = { bound: vev.bound, checked_externally: vev.checked_externally, result: vev.reason, external: vev.external || null };
    if (!vev.ok) refuse("evidence_invalid", "the outcome's evidence pointer is malformed or was not confirmed by the injected lookup", { reason: vev.reason });
    else if (vev.bound && !vev.checked_externally) note("evidence_bound_unchecked", "the provider committed to an evidence pointer but no external lookup ran; a reader must check it in the named system");
    else if (!vev.bound) note("no_evidence_bound", "the outcome carries no independently checkable pointer; it rests on the provider's signed claim alone");
  } else {
    layers.evidence = { bound: false, checked_externally: false, result: "no_receipt", external: null };
  }

  // ---- 4. linkage (digest-bound carriage from observation to the reconciled receipt) ----
  if (observations.length && reconciledReceipt) {
    const rid = receiptId(reconciledReceipt);
    let links = 0; const bad = [];
    observations.forEach((o, i) => {
      const ref = o && o.conduct ? o.conduct.detail_ref : null;
      if (typeof ref === "string" && ref.startsWith(LINK_PREFIX)) { links++; const named = ref.slice(LINK_PREFIX.length); if (named !== rid) bad.push({ index: i, seq: o.hop && o.hop.seq, named }); }
    });
    layers.linkage = { links, mismatched: bad.length };
    if (bad.length) refuse("linkage_receipt_mismatch", "an observation names an execution receipt by digest that is not the reconciled receipt", { records: bad });
    if (links === 0) note("no_digest_link", "no observation names the execution receipt by digest; the layers verify independently but are not linked");
  } else {
    layers.linkage = { links: 0, mismatched: 0 };
  }

  // ---- 5. verdict and honest scope ----
  const verdict = refusals.length ? "refused" : "accepted";
  const establishes = [];
  if (verdict === "accepted") {
    establishes.push("every presented record carries task_id " + task_id + " (" + idChecks.length + " records)");
    if (layers.delegation.present) {
      establishes.push("each of " + observations.length + " observations recomputes (R2) with a witness structurally distinct from both hop parties (R1)");
      establishes.push("the hop chain is contiguous from seq 0 and every prev_evidence_id resolves to a presented prior-hop observation (R3)");
      establishes.push("per-hop verdicts are aggregated over the full witness set, fail-closed; any disagreement is surfaced in layers.delegation.hop_verdicts, never collapsed (R4)");
      if (requireSigs) establishes.push("each observation carries a valid witness signature and a valid delegator edge signature against the resolved keys");
    }
    if (layers.execution.present) {
      establishes.push("the provider's signed executed_action equals the caller's signed authorization, byte for byte (E1)");
      establishes.push("the receipt hash-references this grant and comes from the executor the grant authorized (E3)");
      establishes.push("executed_at is a strict RFC3339 UTC instant inside the grant window");
      establishes.push("exactly one authentic outcome reconciles for this grant (E2)");
      if (requireSigs) establishes.push("caller_sig and provider_sig verify against the resolved keys");
    }
    if (layers.preflight && layers.preflight.present && layers.preflight.complete) {
      establishes.push("the provider declared its action before execution and that declaration equals the caller authorization (preflight): the action was authorized before it ran");
      if (layers.preflight.declared_matches_executed === true) establishes.push("declared equals authorized equals executed: the pre-execution intent, the grant and the reconciled receipt carry the same action byte for byte");
    }
    if (layers.evidence.bound) {
      const ev = evReceipt.outcome.evidence;
      if (layers.evidence.checked_externally) establishes.push("the outcome's evidence pointer " + ev.kind + ":" + ev.ref + " in " + ev.system + " was confirmed by the injected lookup");
      else establishes.push("the provider committed, under its signature, to evidence pointer " + ev.kind + ":" + ev.ref + " in " + ev.system + "; a reader can check it there without the provider");
    }
    if (layers.linkage.links > 0) establishes.push(layers.linkage.links + " observation(s) name the reconciled receipt by digest and the digest recomputes");
  } else {
    establishes.push("nothing: see refusals");
  }
  const does_not_establish = [
    "that any executed action occurred in the world: E1 compares the provider's signed claim to the caller's signed authorization and has no side-effect oracle",
    "that the reconciled outcome is the real-world outcome: E2 proves recoverability and surfaces equivocation, it does not prove truth",
    "that any witness is unaffiliated with the parties: R1 proves structural distinctness, not independence",
    "that bound evidence exists in its system or says what the provider claims, unless layers.evidence.checked_externally is true, and even then only what the injected lookup reported",
    "anything about time beyond the record contents: this verifier has no clock and saw no anchor; a Bitcoin anchor, if one exists, bounds the records separately",
    "that this is the only provenance these parties produced for this task_id",
  ];
  return {
    schema: "nenrin-provenance-verify-v0", verifier_version: VERIFIER_VERSION, task_id, verdict, refusals, findings, layers, establishes, does_not_establish,
    recompute: {
      offline: "this verifier opens no socket and has no clock; run it yourself on the same records and do not take this operator's word",
      layers: ["../task-delegation-bind-v0/bind.mjs + sign.mjs (R1..R4, witness_sig, edge_sig)", "../task-execution-bind-v0/bind_exec.mjs + sign_exec.mjs (E1..E3, caller_sig, provider_sig)", "../task-execution-bind-v0/outcome_evidence.mjs (evidence pointer shape and optional lookup)"],
      cross_layer: ["every record must carry the same task_id", "an observation's detail_ref nenrin-exec://<receipt_id> must equal receiptId(reconciled receipt)", "if an intent is present, its proposed_action must equal the grant action (preflight) and the reconciled receipt executed_action (declared equals authorized equals executed)"],
    },
  };
}


// ============================== provenance-v0/consume.mjs ==============================
// nenrin-consume-v0 : the read surface a TRUST ENGINE uses to consume NENRIN evidence.
//
// This is the composition seam the competitive picture points at: NENRIN is a neutral EVIDENCE source, and a
// reputation or policy engine (a TrustChain-style trust graph, a PHION-style risk gateway, a SINT-style policy
// gateway, or a caller's own gateway) is the DECISION maker. This surface lets such an engine read one task's
// verified evidence in a single call, in a compact and stable shape, and re-verify all of it itself.
//
// It runs the full provenance verification and PROJECTS it. It computes NO trust score and makes NO allow or
// deny decision. It returns verified FACTS, the CONFLICTS surfaced (disagreement and equivocation, never
// collapsed to the favorable value), the honest LIMITS carried through unchanged, content ANCHORS the engine
// can key on, and the steps to recompute everything offline without trusting this operator.

export const CONSUME_VERSION = "0.1.0";

export function consumeEvidence(input) {
  const p = verifyProvenance(input);
  const L = p.layers;
  const exec = L.execution && L.execution.present && L.execution.complete ? L.execution : null;
  const pre = L.preflight && L.preflight.present && L.preflight.complete ? L.preflight : null;

  // verified FACTS. Each is a fact or null (not asserted), never a score.
  const facts = {
    verified: p.verdict === "accepted",
    authorized_before_execution: pre ? true : null,
    executed_matches_authorization: exec ? exec.pair === "action_bound" : null,
    outcome: exec && exec.outcome ? { status: exec.outcome.status, reconciled: exec.reconciliation === "reconciled" } : null,
    hops: L.delegation && L.delegation.present ? L.delegation.hop_verdicts.map((h) => ({ seq: h.seq, verdict: h.verdict, disagreement: h.verdict === "disagreement" })) : [],
    evidence_pointer: L.evidence && L.evidence.bound ? { bound: true, checked_externally: L.evidence.checked_externally } : { bound: false, checked_externally: false },
    digest_links: L.linkage ? L.linkage.links : 0,
  };

  // CONFLICTS are surfaced, never hidden and never collapsed into a favorable value.
  const conflicts = {
    refused: p.verdict === "refused",
    refusal_codes: p.refusals.map((r) => r.code),
    disagreements: p.findings.filter((f) => f.code === "witness_disagreement").map((f) => ({ seq: f.seq, witnesses: f.witnesses })),
    equivocations: p.refusals.filter((f) => f.code === "execution_equivocation").map((f) => ({ receipt_ids: f.receipt_ids })),
  };

  // content ANCHORS the engine can store and reference, all recomputable from the records.
  const anchors = {
    grant_ref: input && input.grant ? input.grant.grant_ref : null,
    intent_id: input && input.intent ? input.intent.intent_id : null,
    reconciled_receipt_id: exec && exec.receipt_id ? exec.receipt_id : null,
    observation_evidence_ids: (input && Array.isArray(input.observations) ? input.observations : []).map((o) => o && o.evidence_id),
  };

  return {
    schema: "nenrin-consume-v0", consume_version: CONSUME_VERSION, task_id: p.task_id,
    facts, conflicts, anchors,
    does_not_establish: p.does_not_establish,
    contract: "NENRIN returns verified evidence and its honest limits. It computes no trust score and makes no allow or deny decision. The consuming engine reads facts and conflicts and decides for itself. Absence of conflict is not evidence of good conduct; it may mean no evidence was presented.",
    reverify: {
      how: "re-run nenrin-provenance-verify-v0 on the same records with your own resolve and lookup; every hash and signature recomputes offline, with no clock and no network",
      provenance: p.recompute,
    },
    provenance: p,
  };
}

// a minimal posture line for engines that want counts to feed their own model. Counts only. Never a score,
// never a verdict, never a recommendation. A disagreement or equivocation count is surfaced, not smoothed away.
export function postureLine(consumed) {
  const f = consumed.facts, c = consumed.conflicts;
  return {
    task_id: consumed.task_id,
    verified: f.verified,
    hops: f.hops.length,
    disagreement_hops: f.hops.filter((h) => h.disagreement).length,
    equivocations: c.equivocations.length,
    outcome_status: f.outcome ? f.outcome.status : null,
    evidence_checked_externally: f.evidence_pointer.checked_externally,
    note: "counts only; not a score, not a verdict, not a recommendation",
  };
}


// ============================== provenance-v0/candidate_evidence.mjs ==============================
// candidate_evidence.mjs : NENRIN-side interop for reputation-aware agent discovery (a2aproject/A2A#1631) and an
// ordering primitive such as ziolndr's ARBITER. Given a task and several candidate agents, each with its own
// provenance records, it produces a per-candidate verified evidence bundle (nenrin-consume-v0) and assembles a
// run-record skeleton.
//
// It decides NOTHING. It does not choose which candidates are permitted, it does not order them, and it computes
// no trust score. The trust filter decides "permitted"; the orderer (ARBITER) decides the order; NENRIN supplies
// the verifiable material and an anchorable run record so a third party can recompute the permitted set and the
// order rather than trust the operator. permitted and order are left null on purpose.

export const CANDIDATE_EVIDENCE_VERSION = "0.1.0";

export function candidateEvidenceSet(task_id, candidates) {
  const evaluated = candidates.map((c) => {
    const bundle = consumeEvidence(Object.assign({}, c.records, { task_id }));
    return { candidate_id: c.candidate_id, bundle, posture: postureLine(bundle) };
  });
  return {
    schema: "nenrin-candidate-evidence-v0",
    version: CANDIDATE_EVIDENCE_VERSION,
    task_id,
    candidates: evaluated.map((e) => ({
      candidate_id: e.candidate_id,
      verified: e.bundle.facts.verified,
      disagreement_hops: e.posture.disagreement_hops,
      equivocations: e.posture.equivocations,
      outcome_status: e.posture.outcome_status,
      evidence_checked_externally: e.posture.evidence_checked_externally,
      anchors: e.bundle.anchors,
    })),
    contract: "NENRIN supplies verified per-candidate evidence and surfaced conflicts. It does not decide which candidates are permitted, it does not order them, and it computes no trust score. The trust filter decides permitted; the ordering primitive (for example ARBITER) decides order.",
    run_record: {
      task_id,
      evaluated_candidates: evaluated.map((e) => e.candidate_id),
      permitted: null,
      order: null,
      evidence_anchors: evaluated.map((e) => ({ candidate_id: e.candidate_id, anchors: e.bundle.anchors })),
      note: "permitted is filled by the trust filter and order by the orderer; NENRIN records them and can anchor this run_record to Bitcoin so a third party recomputes the permitted set and the returned order rather than trusting the operator",
    },
    does_not_establish: [
      "which candidates are permitted: that is the trust filter's decision, from this evidence and its own policy",
      "the order of the candidates: that is the orderer's output, for example ARBITER, over the permitted set",
      "any trust score: none is computed here, and absence of conflict is not evidence of good conduct",
    ],
    bundles: evaluated.map((e) => e.bundle),
  };
}


// ---- internal import aliases (restored from stripped aliased imports) ----
const verifyObservationSigned = verifySigned;

// ---- did:key resolution (offline; Ed25519 public keys are self-encoded, no network, no key server) ----
const NENRIN_B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
function nenrinB58decode(str) {
  const bytes = [0];
  for (let i = 0; i < str.length; i++) {
    let carry = NENRIN_B58.indexOf(str[i]);
    if (carry < 0) throw new Error("bad base58 char");
    for (let j = 0; j < bytes.length; j++) { carry += bytes[j] * 58; bytes[j] = carry & 0xff; carry >>= 8; }
    while (carry > 0) { bytes.push(carry & 0xff); carry >>= 8; }
  }
  let zeros = 0; while (zeros < str.length && str[zeros] === "1") zeros++;
  const res = [];
  for (let z = 0; z < zeros; z++) res.push(0);
  for (let k = bytes.length - 1; k >= 0; k--) res.push(bytes[k]);
  return Uint8Array.from(res);
}
export function publicKeyFromDidKey(did) {
  if (typeof did !== "string" || !did.startsWith("did:key:z")) throw new Error("not a did:key");
  const payload = nenrinB58decode(did.slice("did:key:z".length));
  if (payload[0] !== 0xed || payload[1] !== 0x01) throw new Error("not an ed25519-pub did:key");
  const raw = Buffer.from(payload.slice(2));
  return createPublicKey({ key: { kty: "OKP", crv: "Ed25519", x: raw.toString("base64url") }, format: "jwk" });
}
export const didKeyResolver = (id) => { try { return publicKeyFromDidKey(id); } catch (e) { return null; } };

// ---- CLI: verify a bundle file offline and print the provenance report ----
function nenrinMain() {
  const path = process.argv[2];
  if (!path) { console.error("usage: node nenrin_verify.mjs <bundle.json>"); process.exit(2); }
  const bundle = JSON.parse(readFileSync(path, "utf8"));
  const input = Object.assign({}, bundle, { resolve: didKeyResolver });
  const report = verifyProvenance(input);
  console.log(JSON.stringify(report, null, 2));
  process.exit(report.verdict === "accepted" ? 0 : 1);
}
let nenrinIsMain = false;
try { nenrinIsMain = process.argv[1] && realpathSync(process.argv[1]) === fileURLToPath(import.meta.url); } catch (e) { nenrinIsMain = false; }
if (nenrinIsMain) nenrinMain();
